# Checks to weekly monitor the status of master.
name: Weekly checks

on:
  schedule:
    # Run every monday on 9:00 in the morning (UTC).
    - cron: "0 9 * * 1"
  # Make it possible to trigger the checks manually.
  workflow_dispatch:

jobs:

  # Check whether the Dockerfile still builds using the latest Docker base images.
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      # Building the Dockerfile includes downloading the IRMA schemes.
      # Therefore, we only run one check at the time.
      max-parallel: 1
      matrix:
        # busybox is not working yet.
        image:
          - "debian:stable"
          - "alpine:latest"
          - "ubuntu:latest"
          - "centos:latest"
          - "amazonlinux:latest"
    steps:
      - uses: actions/checkout@v2

      - name: Build Dockerfile
        run: docker build -t privacybydesign/irma:edge --build-arg BASE_IMAGE=${{ matrix.image }} .

      - name: Test Docker image
        run: docker run privacybydesign/irma:edge version

  analyse:
    uses: ./.github/workflows/codeql-analysis.yml
